"""Public Florida geography for fake addresses. City/ZIP pairs are real
geographic facts; street numbers and people are invented."""

CITIES = [
    ("Jacksonville", "Duval", "32202"),
    ("Miami", "Miami-Dade", "33130"),
    ("Tampa", "Hillsborough", "33602"),
    ("Orlando", "Orange", "32801"),
    ("St. Petersburg", "Pinellas", "33701"),
    ("Hialeah", "Miami-Dade", "33010"),
    ("Port St. Lucie", "St. Lucie", "34952"),
    ("Cape Coral", "Lee", "33904"),
    ("Tallahassee", "Leon", "32301"),
    ("Fort Lauderdale", "Broward", "33301"),
    ("Pembroke Pines", "Broward", "33024"),
    ("Hollywood", "Broward", "33020"),
    ("Gainesville", "Alachua", "32601"),
    ("Miramar", "Broward", "33023"),
    ("Coral Springs", "Broward", "33065"),
    ("Clearwater", "Pinellas", "33755"),
    ("Palm Bay", "Brevard", "32905"),
    ("West Palm Beach", "Palm Beach", "33401"),
    ("Lakeland", "Polk", "33801"),
    ("Pompano Beach", "Broward", "33060"),
    ("Miami Gardens", "Miami-Dade", "33056"),
    ("Davie", "Broward", "33314"),
    ("Boca Raton", "Palm Beach", "33431"),
    ("Sunrise", "Broward", "33313"),
    ("Plantation", "Broward", "33317"),
    ("Fort Myers", "Lee", "33901"),
    ("Deerfield Beach", "Broward", "33441"),
    ("Melbourne", "Brevard", "32901"),
    ("Largo", "Pinellas", "33770"),
    ("Pensacola", "Escambia", "32502"),
    ("Ocala", "Marion", "34470"),
    ("Kissimmee", "Osceola", "34741"),
    ("Homestead", "Miami-Dade", "33030"),
    ("Boynton Beach", "Palm Beach", "33426"),
    ("Sarasota", "Sarasota", "34236"),
    ("Daytona Beach", "Volusia", "32114"),
    ("Delray Beach", "Palm Beach", "33444"),
    ("Naples", "Collier", "34102"),
    ("Sanford", "Seminole", "32771"),
    ("Bradenton", "Manatee", "34205"),
]

SPECIALTIES = [
    ("physician", "MD", "Family Medicine"),
    ("physician", "DO", "Internal Medicine"),
    ("psychiatrist", "MD", "Psychiatry"),
    ("dentist", "DDS", "General Dentistry"),
    ("dentist", "DMD", "Pediatric Dentistry"),
    ("neurology", "MD", "Neurology"),
    ("wsc", "MSW", "Waiver Support Coordination"),
    ("np", "ARNP", "Adult-Gerontology"),
]

CLINIC_KINDS = [
    "Family Practice",
    "Behavioral Health",
    "Dental",
    "Neurology Associates",
    "Community Clinic",
    "Pediatric",
    "Internal Medicine Group",
]

MEDS = [
    ("levetiracetam", "500 mg", "BID"),
    ("lamotrigine", "100 mg", "BID"),
    ("sertraline", "50 mg", "daily"),
    ("atorvastatin", "20 mg", "daily"),
    ("metformin", "500 mg", "BID"),
    ("lisinopril", "10 mg", "daily"),
    ("omeprazole", "20 mg", "daily"),
    ("vitamin D3", "2000 IU", "daily"),
    ("polyethylene glycol", "17 g", "daily"),
    ("melatonin", "3 mg", "QHS"),
    ("tamsulosin", "0.4 mg", "daily"),
    ("gabapentin", "300 mg", "TID"),
    ("albuterol HFA", "90 mcg", "PRN"),
    ("cetirizine", "10 mg", "daily"),
    ("amlodipine", "5 mg", "daily"),
]
