"""Invented generic formulary for training.

Names are *not* real INNs or brands. They rhyme with common group-home
classes so MAR UIs look realistic without quoting a marketed product.
"""

from __future__ import annotations

from typing import TypedDict


class FakeDrug(TypedDict):
    code: str
    generic_name: str
    brand_synth: str
    therapeutic_class: str
    used_for: str
    indication: str
    form: str
    strength: str
    strength_unit: str
    route: str
    dose_amount: str
    dose_unit: str
    frequency: str
    scheduled_times: str
    directions: str
    warnings: str
    side_effects: str
    contraindications: str
    storage: str
    prn: bool
    prn_reason: str
    quantity: int
    refills: int
    ndc_synth: str
    rx_otc: str


def _d(**kwargs) -> FakeDrug:
    base: FakeDrug = {
        "code": "",
        "generic_name": "",
        "brand_synth": "",
        "therapeutic_class": "",
        "used_for": "",
        "indication": "",
        "form": "tablet",
        "strength": "1",
        "strength_unit": "mg",
        "route": "PO",
        "dose_amount": "1",
        "dose_unit": "tablet",
        "frequency": "daily",
        "scheduled_times": "08:00",
        "directions": "Take by mouth as directed.",
        "warnings": "Training product only — not for human use.",
        "side_effects": "Drowsiness, GI upset (simulated).",
        "contraindications": "Known hypersensitivity to this training compound.",
        "storage": "Room temperature 20–25°C, dry.",
        "prn": False,
        "prn_reason": "",
        "quantity": 30,
        "refills": 5,
        "ndc_synth": "",
        "rx_otc": "Rx",
    }
    base.update(kwargs)  # type: ignore[typeddict-item]
    return base


# Ordered catalog. code SYNTH-RX-00xx is stable across seeds.
FORMULARY: list[FakeDrug] = [
    _d(
        code="SYNTH-RX-0001",
        generic_name="levotiracetam",
        brand_synth="Keppraline-TEST",
        therapeutic_class="anticonvulsant",
        used_for="seizure control",
        indication="Adjunct for simulated partial-onset seizures.",
        form="tablet",
        strength="500",
        strength_unit="mg",
        dose_amount="1",
        dose_unit="tablet",
        frequency="BID",
        scheduled_times="08:00,20:00",
        directions="Take 1 tablet by mouth twice daily with water.",
        warnings="Do not stop abruptly in training scenarios.",
        side_effects="Irritability, somnolence (simulated).",
        ndc_synth="99999-0001-30",
        quantity=60,
    ),
    _d(
        code="SYNTH-RX-0002",
        generic_name="lamotigene",
        brand_synth="Lamictest",
        therapeutic_class="anticonvulsant / mood stabilizer",
        used_for="seizure and mood stabilization",
        indication="Simulated maintenance for bipolar-spectrum and seizure labs.",
        form="tablet",
        strength="100",
        strength_unit="mg",
        frequency="BID",
        scheduled_times="08:00,20:00",
        directions="Take 1 tablet by mouth twice daily.",
        warnings="Titrate slowly in training protocols.",
        side_effects="Rash (training flag — hold and notify).",
        ndc_synth="99999-0002-60",
        quantity=60,
    ),
    _d(
        code="SYNTH-RX-0003",
        generic_name="sertraloxine",
        brand_synth="Zolofake",
        therapeutic_class="SSRI",
        used_for="mood / anxiety",
        indication="Simulated major depressive or anxiety disorder.",
        form="tablet",
        strength="50",
        strength_unit="mg",
        frequency="daily",
        scheduled_times="08:00",
        directions="Take 1 tablet by mouth every morning.",
        side_effects="Nausea, insomnia (simulated).",
        ndc_synth="99999-0003-30",
    ),
    _d(
        code="SYNTH-RX-0004",
        generic_name="valproexine",
        brand_synth="Depakote-TEST",
        therapeutic_class="anticonvulsant",
        used_for="seizure / mood",
        indication="Simulated mixed seizure and mood-stabilizer labs.",
        form="delayed-release tablet",
        strength="250",
        strength_unit="mg",
        frequency="BID",
        scheduled_times="08:00,20:00",
        directions="Swallow whole. Do not crush.",
        warnings="Monitor simulated LFTs in training notes.",
        ndc_synth="99999-0004-60",
        quantity=60,
    ),
    _d(
        code="SYNTH-RX-0005",
        generic_name="risperidole",
        brand_synth="RisperTEST",
        therapeutic_class="atypical antipsychotic",
        used_for="behavioral support",
        indication="Simulated irritability associated with developmental disability.",
        form="tablet",
        strength="1",
        strength_unit="mg",
        frequency="BID",
        scheduled_times="08:00,20:00",
        directions="Take 1 tablet by mouth twice daily.",
        warnings="Fall-risk training flag.",
        ndc_synth="99999-0005-60",
        quantity=60,
    ),
    _d(
        code="SYNTH-RX-0006",
        generic_name="olanzipine",
        brand_synth="ZypreTEST",
        therapeutic_class="atypical antipsychotic",
        used_for="mood / psychosis training",
        indication="Simulated schizophrenia-spectrum or bipolar maintenance.",
        form="tablet",
        strength="5",
        strength_unit="mg",
        frequency="QHS",
        scheduled_times="20:00",
        directions="Take 1 tablet by mouth at bedtime.",
        side_effects="Weight gain, sedation (simulated).",
        ndc_synth="99999-0006-30",
    ),
    _d(
        code="SYNTH-RX-0007",
        generic_name="quetiapine-sim",
        brand_synth="SeroTEST",
        therapeutic_class="atypical antipsychotic",
        used_for="mood / sleep training",
        indication="Simulated bipolar depression adjunct or insomnia lab.",
        form="tablet",
        strength="25",
        strength_unit="mg",
        frequency="QHS",
        scheduled_times="20:00",
        directions="Take 1 tablet by mouth at bedtime.",
        ndc_synth="99999-0007-30",
    ),
    _d(
        code="SYNTH-RX-0008",
        generic_name="aripiprazim",
        brand_synth="AbiliTEST",
        therapeutic_class="atypical antipsychotic",
        used_for="mood / irritability",
        indication="Simulated adjunct for irritability.",
        form="tablet",
        strength="2",
        strength_unit="mg",
        frequency="daily",
        scheduled_times="08:00",
        directions="Take 1 tablet by mouth every morning.",
        ndc_synth="99999-0008-30",
    ),
    _d(
        code="SYNTH-RX-0009",
        generic_name="metformex",
        brand_synth="Glucophage-TEST",
        therapeutic_class="biguanide",
        used_for="blood sugar",
        indication="Simulated type 2 diabetes mellitus.",
        form="tablet",
        strength="500",
        strength_unit="mg",
        frequency="BID",
        scheduled_times="08:00,20:00",
        directions="Take 1 tablet by mouth twice daily with meals.",
        warnings="Hold if simulated NPO / GI illness protocol.",
        side_effects="GI upset (simulated).",
        ndc_synth="99999-0009-60",
        quantity=60,
    ),
    _d(
        code="SYNTH-RX-0010",
        generic_name="glipizide-sim",
        brand_synth="Glucotest",
        therapeutic_class="sulfonylurea",
        used_for="blood sugar",
        indication="Simulated type 2 diabetes.",
        form="tablet",
        strength="5",
        strength_unit="mg",
        frequency="daily",
        scheduled_times="08:00",
        directions="Take 1 tablet by mouth 30 minutes before breakfast.",
        warnings="Hypoglycemia training flag.",
        ndc_synth="99999-0010-30",
    ),
    _d(
        code="SYNTH-RX-0011",
        generic_name="lisinoprate",
        brand_synth="Prinivil-TEST",
        therapeutic_class="ACE inhibitor",
        used_for="blood pressure",
        indication="Simulated hypertension.",
        form="tablet",
        strength="10",
        strength_unit="mg",
        frequency="daily",
        scheduled_times="08:00",
        directions="Take 1 tablet by mouth every morning.",
        warnings="Check BP before dose in training MAR.",
        ndc_synth="99999-0011-30",
    ),
    _d(
        code="SYNTH-RX-0012",
        generic_name="amlodipane",
        brand_synth="NorvaTEST",
        therapeutic_class="calcium channel blocker",
        used_for="blood pressure",
        indication="Simulated hypertension / angina lab.",
        form="tablet",
        strength="5",
        strength_unit="mg",
        frequency="daily",
        scheduled_times="08:00",
        directions="Take 1 tablet by mouth daily.",
        ndc_synth="99999-0012-30",
    ),
    _d(
        code="SYNTH-RX-0013",
        generic_name="atorvastine",
        brand_synth="Lipitest",
        therapeutic_class="statin",
        used_for="cholesterol",
        indication="Simulated hyperlipidemia.",
        form="tablet",
        strength="20",
        strength_unit="mg",
        frequency="QHS",
        scheduled_times="20:00",
        directions="Take 1 tablet by mouth at bedtime.",
        ndc_synth="99999-0013-30",
    ),
    _d(
        code="SYNTH-RX-0014",
        generic_name="omeprazone",
        brand_synth="PrilotesT",
        therapeutic_class="PPI",
        used_for="acid reflux",
        indication="Simulated GERD / ulcer prophylaxis.",
        form="capsule",
        strength="20",
        strength_unit="mg",
        dose_unit="capsule",
        frequency="daily",
        scheduled_times="08:00",
        directions="Take 1 capsule by mouth 30 minutes before breakfast.",
        ndc_synth="99999-0014-30",
    ),
    _d(
        code="SYNTH-RX-0015",
        generic_name="polyethyline glycol-sim",
        brand_synth="MiraTEST",
        therapeutic_class="osmotic laxative",
        used_for="constipation",
        indication="Simulated occasional constipation.",
        form="powder",
        strength="17",
        strength_unit="g",
        dose_amount="17",
        dose_unit="g",
        route="PO",
        frequency="daily",
        scheduled_times="08:00",
        directions="Mix 17 g in 8 oz water; drink once daily.",
        rx_otc="OTC-training",
        ndc_synth="99999-0015-14",
        quantity=14,
    ),
    _d(
        code="SYNTH-RX-0016",
        generic_name="docusate-sim",
        brand_synth="Colace-TEST",
        therapeutic_class="stool softener",
        used_for="constipation",
        indication="Simulated hard stools.",
        form="capsule",
        strength="100",
        strength_unit="mg",
        dose_unit="capsule",
        frequency="BID",
        scheduled_times="08:00,20:00",
        directions="Take 1 capsule by mouth twice daily.",
        rx_otc="OTC-training",
        ndc_synth="99999-0016-60",
        quantity=60,
    ),
    _d(
        code="SYNTH-RX-0017",
        generic_name="gabapentol",
        brand_synth="Neurontest",
        therapeutic_class="neuropathic agent",
        used_for="nerve pain / adjunct seizure",
        indication="Simulated neuropathic pain.",
        form="capsule",
        strength="300",
        strength_unit="mg",
        dose_unit="capsule",
        frequency="TID",
        scheduled_times="08:00,14:00,20:00",
        directions="Take 1 capsule by mouth three times daily.",
        ndc_synth="99999-0017-90",
        quantity=90,
    ),
    _d(
        code="SYNTH-RX-0018",
        generic_name="baclofene",
        brand_synth="Lioresal-TEST",
        therapeutic_class="muscle relaxant",
        used_for="spasticity",
        indication="Simulated spasticity in cerebral palsy training cases.",
        form="tablet",
        strength="10",
        strength_unit="mg",
        frequency="TID",
        scheduled_times="08:00,14:00,20:00",
        directions="Take 1 tablet by mouth three times daily.",
        ndc_synth="99999-0018-90",
        quantity=90,
    ),
    _d(
        code="SYNTH-RX-0019",
        generic_name="tizanidine-sim",
        brand_synth="ZanaTEST",
        therapeutic_class="muscle relaxant",
        used_for="spasticity",
        indication="Simulated muscle spasm.",
        form="tablet",
        strength="2",
        strength_unit="mg",
        frequency="TID",
        scheduled_times="08:00,14:00,20:00",
        directions="Take 1 tablet by mouth three times daily.",
        warnings="Sedation training flag.",
        ndc_synth="99999-0019-90",
        quantity=90,
    ),
    _d(
        code="SYNTH-RX-0020",
        generic_name="albuterol-sim HFA",
        brand_synth="Ventest HFA",
        therapeutic_class="short-acting beta agonist",
        used_for="wheezing / rescue",
        indication="Simulated bronchospasm.",
        form="inhaler",
        strength="90",
        strength_unit="mcg",
        route="inhaled",
        dose_amount="2",
        dose_unit="puffs",
        frequency="PRN",
        scheduled_times="",
        directions="Inhale 2 puffs as needed for wheezing. Max 4 times / 24 h in training.",
        prn=True,
        prn_reason="wheezing / shortness of breath",
        ndc_synth="99999-0020-01",
        quantity=1,
        refills=2,
    ),
    _d(
        code="SYNTH-RX-0021",
        generic_name="cetirizine-sim",
        brand_synth="ZyrTEST",
        therapeutic_class="antihistamine",
        used_for="allergies",
        indication="Simulated allergic rhinitis.",
        form="tablet",
        strength="10",
        strength_unit="mg",
        frequency="daily",
        scheduled_times="20:00",
        directions="Take 1 tablet by mouth at bedtime.",
        rx_otc="OTC-training",
        ndc_synth="99999-0021-30",
    ),
    _d(
        code="SYNTH-RX-0022",
        generic_name="loratadine-sim",
        brand_synth="Claritin-TEST",
        therapeutic_class="antihistamine",
        used_for="allergies",
        indication="Simulated seasonal allergies.",
        form="tablet",
        strength="10",
        strength_unit="mg",
        frequency="daily",
        scheduled_times="08:00",
        directions="Take 1 tablet by mouth daily.",
        rx_otc="OTC-training",
        ndc_synth="99999-0022-30",
    ),
    _d(
        code="SYNTH-RX-0023",
        generic_name="cholecalciferol-sim",
        brand_synth="D3-TEST",
        therapeutic_class="vitamin",
        used_for="vitamin D",
        indication="Simulated vitamin D insufficiency.",
        form="capsule",
        strength="2000",
        strength_unit="IU",
        dose_unit="capsule",
        frequency="daily",
        scheduled_times="08:00",
        directions="Take 1 capsule by mouth daily with food.",
        rx_otc="OTC-training",
        ndc_synth="99999-0023-90",
        quantity=90,
    ),
    _d(
        code="SYNTH-RX-0024",
        generic_name="multivitamin-sim",
        brand_synth="TheraTEST",
        therapeutic_class="vitamin",
        used_for="nutrition support",
        indication="Simulated general supplementation.",
        form="tablet",
        strength="1",
        strength_unit="tab",
        frequency="daily",
        scheduled_times="08:00",
        directions="Take 1 tablet by mouth daily with breakfast.",
        rx_otc="OTC-training",
        ndc_synth="99999-0024-30",
    ),
    _d(
        code="SYNTH-RX-0025",
        generic_name="levothyrox-sim",
        brand_synth="Synthroid-TEST",
        therapeutic_class="thyroid hormone",
        used_for="thyroid",
        indication="Simulated hypothyroidism.",
        form="tablet",
        strength="50",
        strength_unit="mcg",
        frequency="daily",
        scheduled_times="06:30",
        directions="Take 1 tablet by mouth on empty stomach, 30 min before food.",
        ndc_synth="99999-0025-30",
    ),
    _d(
        code="SYNTH-RX-0026",
        generic_name="tamsulosin-sim",
        brand_synth="Flomax-TEST",
        therapeutic_class="alpha blocker",
        used_for="urinary flow",
        indication="Simulated BPH.",
        form="capsule",
        strength="0.4",
        strength_unit="mg",
        dose_unit="capsule",
        frequency="daily",
        scheduled_times="20:00",
        directions="Take 1 capsule by mouth 30 minutes after the same meal daily.",
        ndc_synth="99999-0026-30",
    ),
    _d(
        code="SYNTH-RX-0027",
        generic_name="oxybutynin-sim",
        brand_synth="Ditropan-TEST",
        therapeutic_class="anticholinergic",
        used_for="bladder",
        indication="Simulated overactive bladder.",
        form="tablet",
        strength="5",
        strength_unit="mg",
        frequency="BID",
        scheduled_times="08:00,20:00",
        directions="Take 1 tablet by mouth twice daily.",
        warnings="Dry mouth / constipation training flag.",
        ndc_synth="99999-0027-60",
        quantity=60,
    ),
    _d(
        code="SYNTH-RX-0028",
        generic_name="melatonex",
        brand_synth="SleepTEST",
        therapeutic_class="sleep aid",
        used_for="sleep",
        indication="Simulated insomnia / sleep-onset delay.",
        form="tablet",
        strength="3",
        strength_unit="mg",
        frequency="QHS",
        scheduled_times="20:00",
        directions="Take 1 tablet by mouth 30 minutes before bedtime.",
        rx_otc="OTC-training",
        prn=True,
        prn_reason="difficulty falling asleep",
        ndc_synth="99999-0028-30",
    ),
    _d(
        code="SYNTH-RX-0029",
        generic_name="acetaminophim",
        brand_synth="Tylenol-TEST",
        therapeutic_class="analgesic / antipyretic",
        used_for="pain / fever",
        indication="Simulated mild pain or fever.",
        form="tablet",
        strength="500",
        strength_unit="mg",
        dose_amount="1",
        frequency="PRN",
        scheduled_times="",
        directions="Take 1 tablet by mouth every 6 hours as needed. Max 3 g / 24 h in training.",
        prn=True,
        prn_reason="pain or fever ≥ 100.4 F",
        rx_otc="OTC-training",
        ndc_synth="99999-0029-100",
        quantity=100,
        refills=1,
    ),
    _d(
        code="SYNTH-RX-0030",
        generic_name="ibuprofene-sim",
        brand_synth="Advil-TEST",
        therapeutic_class="NSAID",
        used_for="pain / inflammation",
        indication="Simulated musculoskeletal pain.",
        form="tablet",
        strength="200",
        strength_unit="mg",
        frequency="PRN",
        scheduled_times="",
        directions="Take 1 tablet by mouth every 6–8 hours as needed with food.",
        prn=True,
        prn_reason="pain or swelling",
        warnings="GI bleed training flag — hold if black stools.",
        rx_otc="OTC-training",
        ndc_synth="99999-0030-50",
        quantity=50,
    ),
    _d(
        code="SYNTH-RX-0031",
        generic_name="hydroxyzine-sim",
        brand_synth="Vistaril-TEST",
        therapeutic_class="antihistamine",
        used_for="anxiety / itch",
        indication="Simulated pruritus or situational anxiety.",
        form="capsule",
        strength="25",
        strength_unit="mg",
        dose_unit="capsule",
        frequency="PRN",
        scheduled_times="",
        directions="Take 1 capsule by mouth every 6 hours as needed.",
        prn=True,
        prn_reason="itching or agitation",
        ndc_synth="99999-0031-30",
    ),
    _d(
        code="SYNTH-RX-0032",
        generic_name="clonidine-sim",
        brand_synth="Catapres-TEST",
        therapeutic_class="alpha agonist",
        used_for="blood pressure / ADHD training",
        indication="Simulated hypertension or ADHD adjunct.",
        form="tablet",
        strength="0.1",
        strength_unit="mg",
        frequency="BID",
        scheduled_times="08:00,20:00",
        directions="Take 1 tablet by mouth twice daily.",
        warnings="Do not stop abruptly in training.",
        ndc_synth="99999-0032-60",
        quantity=60,
    ),
    _d(
        code="SYNTH-RX-0033",
        generic_name="furosemix",
        brand_synth="Lasix-TEST",
        therapeutic_class="loop diuretic",
        used_for="fluid / edema",
        indication="Simulated edema or CHF lab.",
        form="tablet",
        strength="20",
        strength_unit="mg",
        frequency="daily",
        scheduled_times="08:00",
        directions="Take 1 tablet by mouth in the morning.",
        warnings="Monitor simulated potassium.",
        ndc_synth="99999-0033-30",
    ),
    _d(
        code="SYNTH-RX-0034",
        generic_name="potassium chlorix",
        brand_synth="K-Dur-TEST",
        therapeutic_class="electrolyte",
        used_for="potassium replacement",
        indication="Simulated hypokalemia prophylaxis with diuretic.",
        form="tablet",
        strength="10",
        strength_unit="mEq",
        frequency="daily",
        scheduled_times="08:00",
        directions="Take 1 tablet by mouth daily with food. Swallow whole.",
        ndc_synth="99999-0034-30",
    ),
    _d(
        code="SYNTH-RX-0035",
        generic_name="carbamazepim",
        brand_synth="Tegretol-TEST",
        therapeutic_class="anticonvulsant",
        used_for="seizure",
        indication="Simulated focal seizures.",
        form="tablet",
        strength="200",
        strength_unit="mg",
        frequency="BID",
        scheduled_times="08:00,20:00",
        directions="Take 1 tablet by mouth twice daily.",
        warnings="CBC training flag.",
        ndc_synth="99999-0035-60",
        quantity=60,
    ),
    _d(
        code="SYNTH-RX-0036",
        generic_name="topiramine",
        brand_synth="Topamax-TEST",
        therapeutic_class="anticonvulsant",
        used_for="seizure / migraine training",
        indication="Simulated seizure or migraine prophylaxis.",
        form="tablet",
        strength="25",
        strength_unit="mg",
        frequency="BID",
        scheduled_times="08:00,20:00",
        directions="Take 1 tablet by mouth twice daily.",
        ndc_synth="99999-0036-60",
        quantity=60,
    ),
    _d(
        code="SYNTH-RX-0037",
        generic_name="poly-vit mineral-sim",
        brand_synth="Centrum-TEST",
        therapeutic_class="vitamin",
        used_for="nutrition",
        indication="Simulated dietary gap.",
        form="tablet",
        strength="1",
        strength_unit="tab",
        frequency="daily",
        scheduled_times="08:00",
        directions="Take 1 tablet by mouth with breakfast.",
        rx_otc="OTC-training",
        ndc_synth="99999-0037-30",
    ),
    _d(
        code="SYNTH-RX-0038",
        generic_name="nystatin-sim susp",
        brand_synth="Mycostatin-TEST",
        therapeutic_class="antifungal",
        used_for="oral thrush",
        indication="Simulated oropharyngeal candidiasis.",
        form="suspension",
        strength="100000",
        strength_unit="units/mL",
        route="PO swish",
        dose_amount="5",
        dose_unit="mL",
        frequency="QID",
        scheduled_times="08:00,12:00,16:00,20:00",
        directions="Swish 5 mL for 30 seconds and swallow, four times daily.",
        ndc_synth="99999-0038-60",
        quantity=60,
        refills=1,
    ),
    _d(
        code="SYNTH-RX-0039",
        generic_name="hydrocortisone-sim 1%",
        brand_synth="Cortaid-TEST",
        therapeutic_class="topical corticosteroid",
        used_for="skin inflammation",
        indication="Simulated dermatitis.",
        form="cream",
        strength="1",
        strength_unit="%",
        route="topical",
        dose_amount="thin film",
        dose_unit="application",
        frequency="BID",
        scheduled_times="08:00,20:00",
        directions="Apply a thin film to affected area twice daily.",
        rx_otc="OTC-training",
        ndc_synth="99999-0039-15",
        quantity=1,
        refills=2,
    ),
    _d(
        code="SYNTH-RX-0040",
        generic_name="polyethylene glycol-sim plus electrolytes",
        brand_synth="GoLYTELY-TEST",
        therapeutic_class="bowel prep",
        used_for="bowel cleanout (training)",
        indication="Simulated bowel prep — not a standing home med.",
        form="solution",
        strength="240",
        strength_unit="mL",
        route="PO",
        dose_amount="240",
        dose_unit="mL",
        frequency="PRN",
        scheduled_times="",
        directions="Drink 240 mL every 10 minutes until gone, per training protocol.",
        prn=True,
        prn_reason="ordered bowel prep only",
        ndc_synth="99999-0040-04",
        quantity=4,
        refills=0,
    ),
]


assert len({d["code"] for d in FORMULARY}) == len(FORMULARY)
assert len({d["generic_name"] for d in FORMULARY}) == len(FORMULARY)
